const SelectorsCss = {
    idBtnStart: '#btn-start',
    idMinValue: '#minValue',
    idMaxValue: '#maxValue',
    idAttempts: '#attempts',
    classStartPage: '.start-page',
    classGamePage: '.game-page',
    classGreetings: '.greetings',
    classTotalNumbersOfAttempts: '.total-number-of-attempts',
    classGenerateBtn: '.btn-generate',
    idUserValue: '#userValue',
    classOut: '.out',
    classImg: '.img',
    classRemainingAttempts: '.remaining-attempts',
    classBtnExit: '.btn-exit',
    classError: '.error',
    classRulesWrapper: '.rules-wrapper',
    classInstraction: '.instruction',
    classContainer: '.container',
    idChangeSubjects: '#btn-change-subject',
    idTheme: '#theme',
    idBtnClear: '#btn-clear',
    idLang: '#lang',
    title: 'title',
    classRules: '.rules',
    classParagraphInstrationOne: '.paragraph_instruction_one',
    classParagraphInstrationTwo: '.paragraph_instruction_two',
    classOffer: '.offer',
    classInput: '.input'

};

const ElementsDom = {
    startBtn: document.querySelector(SelectorsCss.idBtnStart),
    inputMin: document.querySelector(SelectorsCss.idMinValue),
    inputMax: document.querySelector(SelectorsCss.idMaxValue),
    inputAttempts: document.querySelector(SelectorsCss.idAttempts),
    sectionStartPage: document.querySelector(SelectorsCss.classStartPage),
    sectionGamePage: document.querySelector(SelectorsCss.classGamePage),
    divGreetings: document.querySelector(SelectorsCss.classGreetings),
    totalNumbersOfAttempts: document.querySelector(SelectorsCss.classTotalNumbersOfAttempts),
    generateBtn: document.querySelector(SelectorsCss.classGenerateBtn),
    inputUser: document.querySelector(SelectorsCss.idUserValue),
    divOut: document.querySelector(SelectorsCss.classOut),
    divImg: document.querySelectorAll(SelectorsCss.classImg),
    remainingAttempts: document.querySelector(SelectorsCss.classRemainingAttempts),
    exitBtn: document.querySelector(SelectorsCss.classBtnExit),
    blocksTextError: document.querySelectorAll(SelectorsCss.classError),
    questionIcon: document.querySelector(SelectorsCss.classRulesWrapper),
    instruction: document.querySelector(SelectorsCss.classInstraction),
    windowElement: document.querySelector(SelectorsCss.classContainer),
    switchMode: document.querySelector(SelectorsCss.idChangeSubjects),
    theme: document.querySelector(SelectorsCss.idTheme),
    btnClear: document.querySelector(SelectorsCss.idBtnClear),
    selectLang: document.querySelector(SelectorsCss.idLang),
    title: document.querySelector(SelectorsCss.title),
    inputs: document.querySelectorAll(SelectorsCss.classInput)
};

